name: totvplus
description: TOTV+ TV — مشغّل خفيف لشاشات الأندرويد والتلفاز
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  video_player: ^2.9.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  audioplayers: ^6.1.0
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/intro.wav
    - assets/sounds/tap.wav
